name: Update Contributors

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run script
        run: node generate-contributors-json.js

      - name: Commit and push if changes
        run: |
          # Check for changes to contributors.json
          if git diff --exit-code --name-only | grep 'src/contributors.json'; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add src/contributors.json
            git commit -m "Update contributors.json"
            git push
          else
            echo "No changes to contributors.json, skipping commit and push."
          fi
